name: cd on github

on:
  push:
    branches: [ "ReactApp" ]
  pull_request:
    branches: [ "ReactApp" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.12.2]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Deploy with gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Menyertakan variabel rahasia GITHUB_TOKEN
        REPO: "LandewankFF/Training-CI-CD/"  # Ganti dengan nama pengguna dan nama repository Anda
      run: |
        npm install -g gh-pages  # Menginstal gh-pages secara global jika belum ada
        git remote set-url origin https://github.com/${REPO}.git
        npm run deploy
